name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  upload:
    name: Build & Upload Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          toolchain: 'stable'

      - uses: taiki-e/upload-rust-binary@v1
        with:
          bin: get_dir_hash
          include: |
            LICENSE
            README.md
          target: ${{ matrix.target }}
